### ISSUE TITLE
Create dashboard using Dash or some form of Flask + React or JS or something

### ISSUE THREAD

**Issue by dtingey** [Isaacwilliam4/INSyT#14]
We need to create some kind of visualization that will allow users to see some analytics about the attacks on their system. They should be able to sort by the severity of the attack and the attack type. Maybe see some graphs about attacks over time or be able to look at all attacks and see the generated  analysis and response recommendations. The stack that we use for this is still kinda up in the air. I would recommend using plotly Dash because it is easy to get up and running with that, but we could also use some other form of Flask server/ streamlit app/ whatever we think is best.

**Comment by brightlightkim** [comment]
This is done! :)
